scrape_configs:
  - job_name: 'chat-client'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['chat-client:8080']

  - job_name: 'mcp-server'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: [ 'mcp-server:8081' ]
